### ISSUE TITLE
[FEATURE] Propagate request context

### ISSUE THREAD

**Issue by Kunde21** [open-feature/go-sdk#159]
### Requirements

While the request context was added to the evaluation methods (discussion #72), that is not propagated to the hooks, meaning request-scoped actions using that context can not be taken without hacky solutions like putting the context into the hook hints or forcing those hooks to be in each call site.  

As an example, opentelemetry hooks cannot be registered globally, because they need the trace in the request context.  

[related issue in go-sdk-contrib](https://github.com/open-feature/go-sdk-contrib/issues/116)

**Comment by toddbaert** [comment]
This is a great point. I suspect you're correct.

Luckily, because both `evaluation context` and `hooks` [are still labelled experimental](https://github.com/open-feature/spec/tree/main/specification#document-statuses), we can do some breaking changes here to add the context as  you suggest without a major version bump...

I think we should do that.

@beeme1mr @skyerus @james-milligan How about you guys?

**Comment by skyerus** [comment]
I agree, it's unfortunate that we didn't catch this earlier. Thanks for putting this together!
