### ISSUE TITLE
[FEATURE] Implement Logging Hook 

### ISSUE THREAD

**Issue by toddbaert** [open-feature/go-sdk#284]
### Requirements

- Implement a logging hook as described in appendix A of the OpenFeaure spec: https://github.com/open-feature/spec/blob/main/specification/appendix-a-included-utilities.md#logging-hook
- Remove all logging from evaluation lifecycle (hot path)

Java implementation: https://github.com/open-feature/java-sdk/pull/1084

**Comment by liran2000** [comment]
hi @toddbaert @Kavindu-Dodan,
I am looking at this issue,
I think it can be implemented via [slog](https://pkg.go.dev/log/slog) from standard GO library, but as it started since GO 1.21 and _go-sdk_ is still at GO 1.20, PR can be prepared, and can be merged later when _go-sdk_ move to GO 1.21.
what do you think ? and when _go-sdk_ planned to move to GO 1.21 ?

**Comment by Kavindu-Dodan** [comment]
@liran2000 the SDK should already be on Go 1.22 as latest supported versions are 1.22 & 1.23. So I don't think this is a blocker.
