### ISSUE TITLE
[FEATURE] Improve default error logging

### ISSUE THREAD

**Issue by rcrowe** [open-feature/go-sdk#94]
### Requirements

By default the leveled logger is only outputting errors, via [log.Println(err)](https://github.com/open-feature/go-sdk/blob/9fbed881195a5e1801a0157309db855bbad2b356/pkg/openfeature/logger.go#L24), which in turn calls the [ProviderResolutionDetail.Error()](https://github.com/open-feature/go-sdk/blob/9fbed881195a5e1801a0157309db855bbad2b356/pkg/openfeature/provider.go#L68).

This combination means you end up with logs that look like `2022/10/07 09:09:08 GENERAL` because only the error code is returned by `Error()`.

My preference would be to not log anything like the other levels do; `Error(...)` would be noop, leaving this to userland to decide what they want logging using `SetLogger`. If not, perhaps the message should include more details & make it clear(er) where it originates from, as when interleaved with other logs it makes hunting the cause down tricky.

Wanted to gather any thoughts & opinions first, but I'd be happy to attempt a PR depending on the outcome of this issue. Felt like a sharp edge and we could improve the out-of-the-box experience.

**Comment by skyerus** [comment]
Thanks for bringing this to attention.

I wonder whether we ought to amend the `ProviderResolutionDetail.Error()` func to append the message to the error code, I agree that in its current state there isn't enough information provided by the default logger to be all that useful.

As for whether the default logger logs or not I'm still leaning towards errors being logged by default as it can be frustrating for something to not be working and seeing no indication of that in the logs. I'd like to hear other opinions on the matter @james-milligan @toddbaert @beeme1mr

**Comment by beeme1mr** [comment]
It sounds like there are two issues here. First, the error log is missing key information in order to be useful. It definitely makes sense to improve that error message (and quickly review other log messages). Second, is the the default logging behavior. I would expect there not to be any logging during normal behavior. Originally, I felt it was a good idea to log errors by default but perhaps that's best left up to the user to decide. This seems like something we can change based on user feedback. If the general consensus is to no-op by default, let's do that.

**Comment by beeme1mr** [comment]
@rcrowe would you be willing to improve the log message? I think that would be a good place to start.

**Comment by beeme1mr** [comment]
Thanks @rcrowe, you change will be included in the [next release](https://github.com/open-feature/go-sdk/pull/95).
